=== DanielDiBe/pcgen/code/src/java/generators/Generator.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % name.attribute
     'name   CDATA   #REQUIRED'
>
<!ENTITY % type.attribute
    'type   (random | ordered)  #REQUIRED'
>
<!ENTITY % facade.attributes
    '%name.attribute;
     %type.attribute;'
>
<!ENTITY % weight.attribute
    'weight CDATA "1"'
>
<!ELEMENT BUILDSET (
    ALIGNMENT_GENERATOR |
    CHARACTER_BUILD |
    RACE_GENERATOR |
    CLASS_GENERATOR|
    STANDARDMODE_GENERATOR|
    PURCHASEMODE_GENERATOR|
    SKILL_GENERATOR|
    ABILITY_BUILD |
    EQUIPMENT_GENERATOR|
    SPELL_GENERATOR|
    TEMPLATE_GENERATOR)+
>
<!ATTLIST BUILDSET mutable (true | false) "false">

<!ELEMENT CHARACTER_BUILD (
    GENDER_GENERATOR,
    (ALIGNMENT_GENERATOR | EXT_GENERATOR),
    (RACE_GENERATOR | EXT_GENERATOR),
    (CLASS_GENERATOR | EXT_GENERATOR),
    (STANDARDMODE_GENERATOR | PURCHASEMODE_GENERATOR | EXT_GENERATOR),
    (SKILL_GENERATOR | EXT_GENERATOR),
    (ABILITY_BUILD | EXT_GENERATOR),
    (EQUIPMENT_GENERATOR | EXT_GENERATOR),
    (SPELL_GENERATOR | EXT_GENERATOR),
    (TEMPLATE_GENERATOR | EXT_GENERATOR),
    SOURCE*
)>

<!ELEMENT EXT_GENERATOR EMPTY>
<!ATTLIST EXT_GENERATOR
    %name.attribute;
    uri CDATA #REQUIRED
>

<!ATTLIST CHARACTER_BUILD %name.attribute;>

<!ELEMENT SOURCE (#PCDATA)>
<!ELEMENT ALIGNMENT_GENERATOR (ALIGNMENT)+>
<!ATTLIST ALIGNMENT_GENERATOR %name.attribute;>
<!ELEMENT ALIGNMENT (#PCDATA)>

<!ELEMENT GENDER_GENERATOR EMPTY>
<!ATTLIST GENDER_GENERATOR
target (Any | Male | Female | Neuter) #REQUIRED>

<!-- RACE_GENERATOR declaration -->
<!ELEMENT RACE_GENERATOR (RACE*, SOURCE*)>
<!ELEMENT RACE (#PCDATA)>
<!ATTLIST RACE_GENERATOR %facade.attributes;>
<!ATTLIST RACE %weight.attribute;>

<!-- CLASS_GENERATOR declaration -->
<!ELEMENT CLASS_GENERATOR (CLASS*,SOURCE*)>
<!ELEMENT CLASS (#PCDATA)>
<!ATTLIST CLASS_GENERATOR %facade.attributes;>
<!ATTLIST CLASS %weight.attribute;>

<!-- PURCHASEMODE_GENERATOR declaration -->
<!ELEMENT PURCHASEMODE_GENERATOR (COST)+>
<!ELEMENT COST (#PCDATA)>
<!ATTLIST PURCHASEMODE_GENERATOR
    %name.attribute;
    points CDATA #REQUIRED
>
<!ATTLIST COST score CDATA #REQUIRED>

<!-- STANDARD_GENERATOR declaration -->
<!ELEMENT STANDARDMODE_GENERATOR (STAT, STAT, STAT, STAT, STAT, STAT)>
<!ELEMENT STAT (#PCDATA)>
<!ATTLIST STANDARDMODE_GENERATOR
    %name.attribute;
    assignable (true | false) #REQUIRED
>

<!-- SKILL_GENERATOR declaration -->
<!ELEMENT SKILL_GENERATOR (SKILL*,SOURCE*)>
<!ELEMENT SKILL (#PCDATA)>
<!ATTLIST SKILL_GENERATOR %facade.attributes;>
<!ATTLIST SKILL %weight.attribute;>

<!-- ABILITY_BUILD declaration -->
<!ELEMENT ABILITY_BUILD ((ABILITY_GENERATOR | EXT_GENERATOR)*,SOURCE*)>
<!ELEMENT ABILITY_GENERATOR (ABILITY)*>
<!ATTLIST ABILITY_BUILD %name.attribute;>
<!ATTLIST ABILITY_GENERATOR
    catagory CDATA #REQUIRED
    %type.attribute;
>
<!ELEMENT ABILITY (#PCDATA)>
<!ATTLIST ABILITY %weight.attribute;>

<!ELEMENT EQUIPMENT_GENERATOR EMPTY>
<!ELEMENT SPELL_GENERATOR EMPTY>
<!ELEMENT TEMPLATE_GENERATOR EMPTY>

=== DanielDiBe/pcgen/code/src/java/generators/DefaultStandardGenerators.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE BUILDSET PUBLIC "PCGEN-GENERATORS" 'Generator.dtd'>
<BUILDSET>
    <EXT_GENERATOR name="High" uri="DefaultPurchaseGenerators.xml"/>
    <STANDARDMODE_GENERATOR name="3d6" assignable="true">
        <STAT>3d6</STAT>
        <STAT>3d6</STAT>
        <STAT>3d6</STAT>
        <STAT>3d6</STAT>
        <STAT>3d6</STAT>
        <STAT>3d6</STAT>
    </STANDARDMODE_GENERATOR>
    <STANDARDMODE_GENERATOR name="4d4" assignable="true">
        <STAT>4d4</STAT>
        <STAT>4d4</STAT>
        <STAT>4d4</STAT>
        <STAT>4d4</STAT>
        <STAT>4d4</STAT>
        <STAT>4d4</STAT>
    </STANDARDMODE_GENERATOR>
    <STANDARDMODE_GENERATOR name="4d6 drop lowest" assignable="true">
        <STAT>roll(4,6,top(3))</STAT>
        <STAT>roll(4,6,top(3))</STAT>
        <STAT>roll(4,6,top(3))</STAT>
        <STAT>roll(4,6,top(3))</STAT>
        <STAT>roll(4,6,top(3))</STAT>
        <STAT>roll(4,6,top(3))</STAT>
    </STANDARDMODE_GENERATOR>
    <STANDARDMODE_GENERATOR name="4d6, reroll 1's" assignable="true">
        <STAT>roll(4,6,reroll(1))</STAT>
        <STAT>roll(4,6,reroll(1))</STAT>
        <STAT>roll(4,6,reroll(1))</STAT>
        <STAT>roll(4,6,reroll(1))</STAT>
        <STAT>roll(4,6,reroll(1))</STAT>
        <STAT>roll(4,6,reroll(1))</STAT>
    </STANDARDMODE_GENERATOR>
    <STANDARDMODE_GENERATOR name="4d6, reroll 1's, drop the lowest" assignable="true">
        <STAT>roll(4,6,top(3),reroll(1))</STAT>
        <STAT>roll(4,6,top(3),reroll(1))</STAT>
        <STAT>roll(4,6,top(3),reroll(1))</STAT>
        <STAT>roll(4,6,top(3),reroll(1))</STAT>
        <STAT>roll(4,6,top(3),reroll(1))</STAT>
        <STAT>roll(4,6,top(3),reroll(1))</STAT>
    </STANDARDMODE_GENERATOR>
    <STANDARDMODE_GENERATOR name="5d6 drop 2 lowest" assignable="true">
        <STAT>roll(5,6,top(3))</STAT>
        <STAT>roll(5,6,top(3))</STAT>
        <STAT>roll(5,6,top(3))</STAT>
        <STAT>roll(5,6,top(3))</STAT>
        <STAT>roll(5,6,top(3))</STAT>
        <STAT>roll(5,6,top(3))</STAT>
    </STANDARDMODE_GENERATOR>
</BUILDSET>
